.prettierrc, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json
- fixed #10 
`prettierrc` を入れた。
設定とかで入れたいものあれば適宜入れてください。
設定内容に特にこだわりはないのでネットで拾ったやつです。
=> フォーマッターの追加

.github/workflows/lint-format.yml
- closes #21 
- github actions frontend/backend lint を分ける
- cache を追加
=> #21 refactor: split lint actions

.github/workflows/lint-format.yml
修正しました〜。
一部 single quote -> double quote なのは editor の format によるものくさい・・
=> prettier でコミットが積まれた時に ci が動かない問題の修正

frontend/src/characters/MyPlayer.ts, frontend/src/config/ingameConfig.ts, frontend/src/items/InnerWall.ts, frontend/src/scenes/Game.ts, frontend/src/scenes/Preloader.ts, frontend/src/types/GameObjectFactory.d.ts, frontend/src/utils/generateMap.ts
これがやりたかった
https://user-images.githubusercontent.com/10017674/209654232-6994eebb-3930-458d-bb34-560de67327b5.mov
innerWall　をクラス定義して実現した
https://user-images.githubusercontent.com/10017674/209654215-1c0e419b-3966-4267-be7b-4ff3e7c183ce.mov
=> inner wall の角を丸くした

backend/src/constants/constants.ts, backend/src/index.ts, backend/src/rooms/GameRoom.ts, backend/src/rooms/schema/GameRoomState.ts, backend/src/rooms/schema/Player.ts, frontend/src/characters/MyPlayer.ts, frontend/src/characters/Player.ts, frontend/src/scenes/Game.ts, frontend/src/types/objects.ts, frontend/src/utils/generateMap.ts, frontend/tsconfig.json, package-lock.json, package.json
[Phaser: Real Time Multiplayer with Colyseus](https://learn.colyseus.io/phaser/index.html) をそのまんまパクってサーバ経由でもそれなりにスムーズに動くようにしました。
innerWall があると、ぶつかって状態が変わるので一旦消してます。
そのうちサーバで生成して、衝突判定もサーバに入れたい
https://user-images.githubusercontent.com/10017674/209854934-e8657302-26b9-4364-b8fa-0a1bd26457d9.mov
=> サーバを経由してもスムーズな動きになるようにした

frontend/src/characters/Player.ts
- closed #58 
https://user-images.githubusercontent.com/10017674/210120852-2fa5e222-6464-407f-b5cd-8aa3c9357376.mov
=> 爆弾をいい位置に置けるようにした

backend/src/constants/constants.ts, frontend/src/anims/BombAnims.ts, frontend/src/config/ingameConfig.ts
- https://github.com/recursion-team-v/bomb/issues/61#issuecomment-1368155534
>  ボムはボムボタンを押してから､140フレーム(2.33秒)後に爆発
ということなので2.33にした
=> 爆弾の爆発時間を2.33secにしconstantssに移した

backend/src/constants/constants.ts, backend/src/rooms/GameEngine.ts, frontend/src/scenes/Game.ts
https://user-images.githubusercontent.com/10017674/210149616-9a92aa86-81c5-429b-a8a0-44436cfe9991.mov
=> サーバとクライアントの場所が同じになるようにした

backend/Dockerfile
https://console.cloud.google.com/logs/query;query=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22bomb%22%0Aresource.labels.revision_name%3D%22bomb-00024-gaq%22;cursorTimestamp=2023-01-03T02:28:29.003817631Z?project=bomb-373115
```
❯ docker run -it --rm bomb:latest
node:internal/modules/cjs/loader:998
throw err;
^
Error: Cannot find module '/work/sk'
at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
at Module._load (node:internal/modules/cjs/loader:841:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:23:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
Node.js v18.12.1
```
=> GCPのデプロイにこけていたのでDockerfile修正

frontend/src/items/Bomb.ts
- fixed #101 
https://user-images.githubusercontent.com/10017674/210495077-8a2da73d-4af5-49a8-be3b-15ad97693039.mov
=> 中央の爆風のサイズを1.2倍にした

backend/src/constants/constants.ts, backend/src/rooms/schema/Map.ts, frontend/src/items/Block.ts, frontend/src/scenes/Game.ts, frontend/src/scenes/Preloader.ts, frontend/src/types/GameObjectFactory.d.ts, frontend/src/utils/drawMap.ts
=> #122 fix generate random blocks

backend/nodemon.json, backend/package-lock.json, backend/package.json
nodemon の調子がとても悪く、restart しても port 競合で再起動しないので
ts-node-dev に乗り換えさせてください
=> nodemon から ts-node-dev に乗り換え

backend/src/game_engine/services/ItemService.ts, backend/src/rooms/GameEngine.ts, frontend/src/characters/MyPlayer.ts, frontend/src/characters/OtherPlayer.ts, frontend/src/characters/Player.ts, frontend/src/scenes/Game.ts, frontend/src/services/Network.ts, frontend/src/types/GameObjectFactory.d.ts
=> #139 プレイヤー動作処理を Game.ts から MyPlayer、OtherPlayer クラスへ移行する

backend/package-lock.json, backend/package.json
=> update colyseus to 0.14.24

backend/src/constants/constants.ts, backend/src/game_engine/collision_handler/blast.ts, backend/src/game_engine/collision_handler/collision_handler.ts, backend/src/game_engine/collision_handler/player.ts, backend/src/interfaces/player.ts, backend/src/rooms/GameRoom.ts, backend/src/rooms/schema/GameState.ts, backend/src/rooms/schema/Player.ts, frontend/src/characters/MyPlayer.ts, frontend/src/characters/OtherPlayer.ts, frontend/src/characters/Player.ts, frontend/src/game_engine/collision_handler/collision_handler.ts, frontend/src/lib/phaserJuice.js, frontend/src/scenes/Game.ts, frontend/tsconfig.json
やったこと
- closed #151
- closed #142
- closed #141
- closed #132
ついでに参加者が0~1になったらゲーム終了するようにしましたが、
ロビーから入って正しくゲーム開始しないとすぐ終了しちゃうのでコメントアウトしてます。
https://user-images.githubusercontent.com/10017674/211156663-ec3cabdb-8fee-46a1-a3dc-21327c2167ad.mov
https://user-images.githubusercontent.com/10017674/211157104-e4d9b03c-8fe7-4673-bb42-9fb2621d1942.mov
光ってる間は無敵時間
https://user-images.githubusercontent.com/10017674/211156693-a124b6fb-6291-47c7-9299-ecf53fc8b385.mov
https://user-images.githubusercontent.com/10017674/211156712-cfc6f8a8-7d2f-4dd3-805b-094452356d33.mov
=> player に hp の概念と関連メソッドの追加

backend/src/constants/constants.ts, backend/src/game_engine/services/blastService.ts, frontend/src/items/Bomb.ts
=> 爆風の範囲を調整した

backend/src/constants/constants.ts, backend/src/game_engine/services/blastService.ts, backend/src/rooms/GameEngine.ts, frontend/src/PhaserGame.ts, frontend/src/characters/Player.ts, frontend/src/items/Block.ts, frontend/src/items/Bomb.ts, frontend/src/items/Item.ts, frontend/src/items/Wall.ts, frontend/src/items/util.ts, frontend/src/scenes/Game.ts, frontend/src/services/Map.ts
サーバ・フロントでロジック同じにしたかったけど matter の罠により無理だった
- closed #146
- closed #152
https://user-images.githubusercontent.com/10017674/211167494-79a03ff9-0d64-4ffb-89a6-842449f44768.mov
爆弾おきまくるとこける模様
=> 爆風をいい感じにするようにした

backend/src/constants/constants.ts, frontend/src/characters/Player.ts, frontend/src/scenes/Game.ts
https://user-images.githubusercontent.com/10017674/211301935-85556cf6-5528-45ca-92bf-bedf3d44eaf0.mov
=> ブロックを破壊するエフェクトの追加

backend/src/game_engine/services/playerService.ts
=> fix: サーバとローカルで微妙にずれるのを修正

frontend/src/characters/MyPlayer.ts, frontend/src/characters/Player.ts
=> アイテムを取得した時だけ音を鳴らす

backend/src/constants/constants.ts
=> 初期のボムの強さを2にした

backend/src/constants/constants.ts, frontend/src/scenes/Preloader.ts, frontend/src/utils/key.ts
=> スマホで爆弾を置くボタンの画像差し替え

backend/src/constants/constants.ts, backend/src/game_engine/collision_handler/blast.ts, backend/src/game_engine/collision_handler/collision_handler.ts, backend/src/game_engine/services/blastService.ts, backend/src/game_engine/services/bombService.ts, backend/src/game_engine/services/playerService.ts, backend/src/interfaces/bomb.ts, backend/src/rooms/GameRoom.ts, backend/src/rooms/schema/Blast.ts, backend/src/rooms/schema/Bomb.ts, backend/src/rooms/schema/GameRoomState.ts, backend/src/rooms/schema/Player.ts, frontend/src/characters/MyPlayer.ts, frontend/src/characters/Player.ts, frontend/src/config/config.ts, frontend/src/events/GameEvents.ts, frontend/src/game_engine/collision_handler/collision_handler.ts, frontend/src/items/Bomb.ts, frontend/src/scenes/Game.ts, frontend/src/services/Bomb.ts, frontend/src/services/Network.ts, frontend/src/types/GameObjectFactory.d.ts
- closed #147
100msec 環境で、爆風（クライアント）と当たり判定（サーバ）はこんな感じ。
https://user-images.githubusercontent.com/10017674/211745128-d1015198-3a8d-4fe5-8eb2-4e2eae227182.mov
ついでにサーバの判定を見えるようにした（debug 機能なので on/off できる)
=> サーバ側での誘爆の処理を実装

backend/src/game_engine/services/blastService.ts, backend/src/game_engine/services/bombService.ts, backend/src/rooms/GameEngine.ts, backend/src/rooms/GameRoom.ts
https://docs.colyseus.io/colyseus/server/timing-events/
ローカルで確認した限りはこれが解決してた
- closed #192
=> サーバ側の時間管理を colyseus おすすめのものに変更

backend/src/constants/constants.ts, backend/src/game_engine/collision_handler/collision_handler.ts, backend/src/rooms/schema/Item.ts, frontend/src/scenes/Game.ts
- closed #145
https://user-images.githubusercontent.com/10017674/211826900-1fb048b6-4cc5-4562-827c-8ad284bc55f9.mov
ブロックと同様にアイテムも同時に破壊される必要があるので、
それは別PRでやります。
=> 爆風でアイテムが破壊される処理を追加

backend/src/rooms/GameRoom.ts, frontend/src/scenes/Game.ts, frontend/src/scenes/GameHeader.ts, frontend/src/services/Block.ts, frontend/src/services/Network.ts
以下を修正
- サーバからルームの終了時間を受け取れてなかったので直した
- ブロックの破壊の時間を↑の時間使うようにした
=> [bugfix] ブロックが壊せないバグを修正

backend/src/rooms/GameRoom.ts, backend/src/utils/gameQueue.ts
- fixed #207
---
- 変なところでキューを削除しているところを修正
- debug 用の queue の size 機能追加
=> [bugfix] 複数の爆弾を置いたときに、最初の爆弾がブロックを壊すと次の爆弾がサーバで爆発しない

backend/src/game_engine/services/blastService.ts, backend/src/rooms/schema/Bomb.ts, frontend/src/items/Bomb.ts, frontend/src/services/Bomb.ts, frontend/src/types/GameObjectFactory.d.ts
- fixed #215 
https://user-images.githubusercontent.com/10017674/212372081-0e7afe29-5254-4bdb-9332-9d5f67172c81.mov
=> アイテムを取得しても既存のボムの強さは変えないようにした

frontend/src/config/config.ts, frontend/src/items/Bomb.ts
- fixed #214 
https://user-images.githubusercontent.com/10017674/212382597-6e753445-68b2-4007-91c3-1c156fecb314.mov
=> 爆発前に爆風の範囲を描画する機能の追加

backend/src/constants/constants.ts, backend/src/game_engine/collision_handler/collision_handler.ts, backend/src/game_engine/collision_handler/player.ts, backend/src/rooms/GameRoom.ts, backend/src/rooms/schema/GameRoomState.ts, backend/src/rooms/schema/Item.ts, frontend/src/scenes/Game.ts, frontend/src/services/Item.ts, frontend/src/services/Network.ts
=> アイテム削除のタイミングをクラサバで同期する

backend/src/constants/constants.ts, backend/src/game_engine/collision_handler/collision_handler.ts, backend/src/game_engine/services/dropWallService.ts, backend/src/rooms/GameRoom.ts, backend/src/rooms/schema/Timer.ts, backend/src/utils/map.ts, frontend/src/items/Wall.ts, frontend/src/scenes/Game.ts, frontend/src/services/Map.ts, frontend/src/services/Network.ts, frontend/src/types/GameObjectFactory.d.ts
https://user-images.githubusercontent.com/10017674/212399254-5b32d1e7-50f6-48d2-8b43-0dcc1c1e1e4c.mov
=> 残り30秒になると壁が降ってくるやつ追加

frontend/src/scenes/Game.ts
=> 死んだユーザが切断するとエラーになる

frontend/src/PhaserGame.ts, frontend/src/config/config.ts, frontend/src/items/Bomb.ts
=> 本番の時はデバッグ無効

frontend/src/config/config.ts, frontend/src/services/Network.ts
=> server url を vercel env から取得する

backend/src/constants/constants.ts, backend/src/rooms/schema/Player.ts, frontend/src/characters/MyPlayer.ts, frontend/src/characters/OtherPlayer.ts, frontend/src/characters/Player.ts
=> 名前を表示するようにした

frontend/src/characters/MyPlayer.ts
=> #225 remove dummy player

frontend/src/characters/Player.ts
=> name label を中央寄せにした

backend/src/constants/constants.ts
=> アイテムが無敵の時間を減らした

frontend/src/characters/Player.ts
=> 正しくアイテム数がヘッダに表示されるようにした

backend/src/rooms/GameRoom.ts, frontend/src/scenes/Lobby.ts
- closes #289 
> Locking the room will remove it from the pool of available rooms for new clients to connect to.
と Colyseus に書かれているため、おそらく reconnect には影響しないと思います
=> ゲーム開始時に部屋をロックする

backend/src/constants/constants.ts, frontend/src/scenes/GameHeader.ts, frontend/src/utils/drawMap.ts
=> ゲーム開始演出後にタイマーをスタートさせる

frontend/src/scenes/GameResult.ts
=> go to lobby を右側にした

frontend/src/utils/usage.ts
https://user-images.githubusercontent.com/10017674/215116224-675db73b-0129-4df9-a52e-a3a94098021c.mov
=> タイトルでボムのアニメーションも入れた

backend/src/constants/constants.ts
=> アイテムの無敵時間を調整

backend/src/constants/constants.ts, frontend/src/utils/usage.ts
=> デフォルトキャラを cat にした

frontend/src/utils/key.ts
=> マルチタップを有効化

frontend/src/scenes/GameHeader.ts
=> volume icon の位置を調整

frontend/src/scenes/GameResult.ts
=> リザルトにもボリュームアイコン追加

backend/src/constants/constants.ts
=> ゲームの時間を2分にした

frontend/src/scenes/GameResult.ts
=> 勝者の名前の位置を微調整

frontend/src/items/Wall.ts
=> 落ちてくるブロックに暫定のアセットを設定

backend/src/game_engine/services/ItemService.ts, frontend/src/items/Item.ts
こうなる。
ちなみにピッタリになるサイズにすると、ブロックと同じ色で微妙になる。
=> アイテムのスケールサイズを変更

frontend/src/config/config.ts, frontend/src/scenes/Game.ts, frontend/src/services/Cloud.ts
=> 雲がいい感じに出るようにした

cloudbuild.yaml
=> change the registry from asia.gcr.io to asia-northeast1-docker.pkg.dev
